---
# Usage: http://ruhoh.com/usage/configure/ 

RuhohSpec: '1.0'
theme : artisteer
production_url : http://www.minimak.org/

posts:
  permalink: /:categories/:title/
  summary_lines: 20
  latest: 10

pages:
  permalink: 'pretty'
