title:    Minimak
tagline:  Minimum Learning, Maximum Efficiency
author:
  name:     Ted Lilley
  email:    ted.lilley@gmail.com
  github:   lilleyt
  twitter:  lilleyt
  feedburner: Minimak

navigation :
  - index.md
  - download.md
  - caveats.md
  - learn.md
  - design.md
  - faq.md
  - blog.md
  - forum.md

download_location: http://www.minimak.org/minimak.zip
