title : MiniMak
tagline: Minimum Learning, Maximum Efficiency
author :
  name : Ted Lilley
  email : ted.lilley@gmail.com
  github : lilleyt
  twitter : lilleyt

navigation :
  - index.md
  - features.md
  - learning.md
  - analysis.md
  - story.md
  - credits.md
