title : Minimak
tagline: Minimum Learning, Maximum Efficiency
author :
  name : Ted Lilley
  email : ted.lilley@gmail.com
  github : lilleyt
  twitter : lilleyt

navigation :
  - index.md
  - download.md
  - learning.md
  - background.md
  - credits.md
